map('n', ',C', ':-1read ~/.config/nvim/template/skel.c<CR>G')
map('n', ',cpp', ':-1read ~/.config/nvim/template/skel.cpp<CR>G')
map('n', ',py', ':-1read ~/.config/nvim/template/skel.py<CR>G')
map('n', ',lua', ':-1read ~/.config/nvim/template/skel.lua<CR>G')
map('n', ',sh', ':-1read ~/.config/nvim/template/skel.sh<CR>G')
map('n', ',mk', ':-1read ~/.config/nvim/template/skel.mk<CR>G')
map('n', ',ms', ':-1read ~/.config/nvim/template/skel.ms<CR>G')
map('n', ',tex', ':-1read ~/.config/nvim/template/skel.tex<CR>G')
map('n', ',rmd', ':-1read ~/.config/nvim/template/skel.rmd<CR>G')
map('n', ',html', ':-1read ~/.config/nvim/template/skel.html<CR>G')

map('n', ',eb', ':read ~/.config/nvim/template/eb.latex<CR>o')
